backend:
  name: git-gateway
  repo: wearethoughtfox/brickhouse # Path to your Github repository
  branch: master # Branch to update (master by default)

media_folder: "images" # Folder where user uploaded files should go

collections:
  - name: "work" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Work" # Used in the UI, ie.: "New Post"
    folder: "_work/" # The path to the folder where the documents are stored
    editor:
      preview: false
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "work"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: true}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "services" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Services" # Used in the UI, ie.: "New Post"
    folder: "_services/" # The path to the folder where the documents are stored
    editor:
      preview: false
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "work"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: true}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: 'pages'
    label: 'Pages'
    editor:
      preview: false
    files:
      - label: 'Home layout'
        name: 'home'
        file: 'index.html'
        fields:
          - { label: 'Title', name: 'title', widget: 'hidden', default: 'about' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
